CC = gcc

CFLAGS = \
	-D_POSIX_C_SOURCE=200809L \
	-Wall \
	-Wextra \
	-std=c11 \
	-Iinclude

LIB_SRC = \
	$(wildcard src/core/*.c) \
	$(wildcard src/causal_sequencer/*.c) \
	$(wildcard src/persistence_log/*.c)

TEST_SRC = \
	$(wildcard tests/*.c)

LOG_TEST_SRC = tests/test_log.c

SRC = \
	$(LIB_SRC) \
	$(TEST_SRC)

OBJ = \
	$(SRC:.c=.o)

LOG_TEST_OBJ = \
	$(LIB_SRC:.c=.o) \
	$(LOG_TEST_SRC:.c=.o)

BIN = bin/test
LOG_TEST_BIN = bin/test_log

all: $(BIN) $(LOG_TEST_BIN)

$(BIN): $(OBJ)
	@mkdir -p bin
	$(CC) $(OBJ) -o $(BIN)

$(LOG_TEST_BIN): $(LOG_TEST_OBJ)
	@mkdir -p bin
	$(CC) $(LOG_TEST_OBJ) -o $(LOG_TEST_BIN)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

run: all
	./$(BIN)
	./$(LOG_TEST_BIN)

clean:
	find src tests -name "*.o" -delete
	rm -rf bin storage

.PHONY: all run clean